# Generated by Django 4.1.13 on 2025-03-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('phones_gadgets', 'Телефоны и гаджеты'), ('home_appliances', 'Бытовая техника'), ('tv_audio_video', 'ТВ, Аудио и Видео'), ('computers', 'Компьютеры'), ('home_goods', 'Товары для дома')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phones_gadgets', 'Телефоны и гаджеты'), ('home_appliances', 'Бытовая техника'), ('tv_audio_video', 'ТВ, Аудио и Видео'), ('computers', 'Компьютеры'), ('home_goods', 'Товары для дома')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.brand')),
            ],
        ),
    ]
