# Generated by Django 4.1.13 on 2025-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_order_brand_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
